version: '3'

services:
  db:
    image: postgres
    volumes:
     - /var/lib/dockerpostgresql/data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
     - "127.0.0.1:8000:8000"
    depends_on:
      - db
