# Generated by Django 2.1.5 on 2019-01-24 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=100, verbose_name='Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Lastname')),
                ('surname', models.CharField(blank=True, default='', max_length=100, verbose_name='Surname')),
                ('player', models.CharField(blank=True, default='', max_length=100, verbose_name='Player')),
                ('dndclass', models.CharField(max_length=100, verbose_name='DnDClass')),
                ('dndarchetype', models.CharField(blank=True, default='', max_length=100, verbose_name='DnDArchetype')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Level')),
                ('str', models.PositiveSmallIntegerField(default=10, verbose_name='STR')),
                ('dex', models.PositiveSmallIntegerField(default=10, verbose_name='DEX')),
                ('con', models.PositiveSmallIntegerField(default=10, verbose_name='CON')),
                ('int', models.PositiveSmallIntegerField(default=10, verbose_name='INT')),
                ('wis', models.PositiveSmallIntegerField(default=10, verbose_name='WIS')),
                ('cha', models.PositiveSmallIntegerField(default=10, verbose_name='CHA')),
                ('save_str', models.BooleanField(default=False, verbose_name='Save STR')),
                ('save_dex', models.BooleanField(default=False, verbose_name='Save DEX')),
                ('save_con', models.BooleanField(default=False, verbose_name='Save CON')),
                ('save_int', models.BooleanField(default=False, verbose_name='Save INT')),
                ('save_wis', models.BooleanField(default=False, verbose_name='Save WIS')),
                ('save_cha', models.BooleanField(default=False, verbose_name='Save CHA')),
                ('ac', models.PositiveSmallIntegerField(default=10, verbose_name='ac')),
                ('initiative', models.PositiveSmallIntegerField(default=10, verbose_name='initiative')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=100, verbose_name='Description')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Bonus')),
                ('stack', models.PositiveIntegerField(default=0, verbose_name='Stack    ')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Character')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('stat', models.CharField(choices=[('STR', 'STR'), ('DEX', 'DEX'), ('CON', 'CON'), ('INT', 'INT'), ('WIS', 'WIS'), ('CHA', 'CHA')], default='STR', max_length=4, verbose_name='Stat')),
                ('mastery', models.BooleanField(default=False, verbose_name='Mastery')),
                ('expertise', models.BooleanField(default=False, verbose_name='Expertise')),
                ('bonus', models.PositiveSmallIntegerField(default=0, verbose_name='Bonus')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Character')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('surname', models.CharField(max_length=100, verbose_name='surname')),
                ('description', models.TextField(max_length=100, verbose_name='Description')),
                ('stat', models.CharField(choices=[('STR', 'STR'), ('DEX', 'DEX'), ('CON', 'CON'), ('INT', 'INT'), ('WIS', 'WIS'), ('CHA', 'CHA')], default='STR', max_length=4, verbose_name='Stat')),
                ('mastery', models.BooleanField(default=False, verbose_name='Mastery')),
                ('bonus', models.PositiveSmallIntegerField(default=0, verbose_name='Bonus')),
                ('dmg', models.CharField(blank=True, default='', max_length=64, verbose_name='Damage')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Character')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ability',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Character'),
        ),
    ]
